version: '3.8'

networks:
  backend:

services:

  backend:
    build: .
    command: python manage.py runserver -b 0.0.0.0:8000
    depends_on:
      - db
    restart: always
    environment:
      - DB_HOST=db
    networks:
      - backend
    volumes:
      - ./stocks_products/:/stocks_products/
    ports:
      - "8000:8000"
    env_file:
      - .env
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    networks:
      - backend
    environment:
      - "POSTGRES_HOST_AUTH_METHOD: trust"
    volumes:
      - ./database:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"


#  nginx: