version: '3.8'

services:

  backend:
    build: .
    image: stocks_products
    container_name: stocks_products
    depends_on:
      - db
    volumes:
      - ./stocks_products/:/stocks_products/
    ports:
      - "8000:8000"
    env_file:
      - .env
  db:
    image: postgres:14.1-alpine
    container_name: postgres_db
    restart: unless-stopped
#    volumes:
#      - ./database:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx
    volumes:
      - ./stocks_products/static/:/stocks_products/static
    ports:
      - "80:80"
    depends_on:
      - backend
      - db